In [17]:
# Exercise 1
# the length of vector
import numpy as np
def comute_vector_length(vector):
  length_of_vector = np.linalg.norm(vector)
  return length_of_vector
vector = np.array([-2,4,9,21])
comute_vector_length(vector)

23.280893453645632

In [18]:
# Dot product
def compute_dot_product(vector_1, vector_2):
   result = np.dot(vector_1, vector_2)
   return result
vector_1 = np.array([0,1,-1,2])
vector_2 = np.array([2,5,1,0])
compute_dot_product(vector_1, vector_2)

4

In [25]:
# Multiplying a vector by a matrix
def matrix_multi_vector(matrix, vector):
  result = np.dot(matrix, vector) # Sử dụng hàm np.dot để tính dot product giữa matrix và vector. Lưu ý vị trí của đối số. Vì A*B khác B*A
  return result
matrix = np.array([[-1, 1,1],
                   [0, -4,9]])
vector = np.array([0,2,1])
matrix_multi_vector(matrix, vector)

array([3, 1])

In [23]:
matrix@vector

array([ 3, -5])

In [26]:
# multiplying matrix by a matrix
def matrix_multi_matrix(matrix_1, matrix_2):
  result = np.dot(matrix_1, matrix_2)
  return result
matrix_1 = np.array([[0,1,2], [2,-3,1]])
matrix_2 = np.array([[1,-3], [6,1], [0,-1]])
matrix_multi_matrix(matrix_1, matrix_2)

array([[  6,  -1],
       [-16, -10]])

In [27]:
m1 = np.eye(3)
m2 = np.array([[1,1,1], [2,2,2], [3,3,3]])
m1@m2

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [28]:
m1 = np.eye(2)
m1 = np.reshape(m1, (-1, 4))[0]
m2 = np.array([[1,1,1,1], [2,2,2,2], [3,3,3,3],[4,4,4,4]])
m1@m2

array([5., 5., 5., 5.])

In [29]:
m1 = np.array([[1,2],[3,4]])
m1 = np.reshape(m1, (-1, 4),"F")[0]
m2 = np.array([[1,1,1,1], [2,2,2,2], [3,3,3,3],[4,4,4,4]])
m1@m2

array([29, 29, 29, 29])

In [32]:
# matrix inverse
def inverse_matrix(matrix):
  try:
    result = np.linalg.inv(matrix)
  except np.linalg.LinAlgError:
    result = np.linalg.pinv(matrix)
  return result
matrix = np.array([[-2,6],[8,-4]])
inverse_matrix(matrix)

array([[0.1 , 0.15],
       [0.2 , 0.05]])

In [ ]:
# Eigenvector and eigenvalue
def compute_eigenvalues_eigenvector(matrix):


In [33]:
# compute eigenvalues and eigenvector

import numpy as np
def compute_eigenvalues_eigenvector(matrix):
  eigenvalues, eigenvectors = np.linalg.eig(matrix)
  return eigenvalues, eigenvectors
matrix = np.array([[0.9, 0.2],[0.1, 0.8]])
compute_eigenvalues_eigenvector(matrix)


(array([1. , 0.7]),
 array([[ 0.89442719, -0.70710678],
        [ 0.4472136 ,  0.70710678]]))

In [34]:
def compute_cosine(v1, v2):
  result = (np.dot(v1,v2))/(np.linalg.norm(v1)*np.linalg.norm(v2))
  return result
v1 = np.array([1,2,3,4])
v2 = np.array([1,0,3,0])
compute_cosine(v1, v2)

0.5773502691896257